# Generated by Django 6.1.1 on 2026-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('image_file_name', models.CharField(help_text='Image file name (e.g., IMG_7493.JPG)', max_length=255, primary_key=True, serialize=False)),
                ('invent_number', models.CharField(blank=True, help_text='Inventory number', max_length=255, null=True)),
                ('invent_img', models.CharField(blank=True, help_text='Inventory image number', max_length=255, null=True)),
                ('high_res_image', models.CharField(blank=True, help_text='High resolution image reference', max_length=255, null=True)),
                ('date', models.DateField(blank=True, help_text='Date associated with the image', null=True)),
                ('id_title', models.CharField(blank=True, help_text='ID title', max_length=255, null=True)),
                ('website_title', models.CharField(blank=True, help_text='Website title', max_length=255, null=True)),
                ('part_of_gallery', models.CharField(blank=True, help_text='Part of a gallery', max_length=255, null=True)),
                ('medium', models.CharField(blank=True, help_text='Art medium', max_length=255, null=True)),
                ('substrate', models.CharField(blank=True, help_text='Substrate material', max_length=255, null=True)),
                ('dimensions_hxwxd', models.CharField(blank=True, help_text='Dimensions (Height x Width x Depth)', max_length=255, null=True)),
                ('orientation', models.CharField(blank=True, help_text='Image orientation', max_length=255, null=True)),
                ('edition', models.CharField(blank=True, help_text='Edition information', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='Location', max_length=255, null=True)),
                ('in_inventory', models.CharField(blank=True, help_text='In inventory status', max_length=255, null=True)),
                ('number_sold', models.IntegerField(blank=True, help_text='Number of items sold', null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price', max_digits=10, null=True)),
                ('cost_of_goods', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of goods', max_digits=10, null=True)),
                ('current_inventory', models.IntegerField(blank=True, help_text='Current inventory count', null=True)),
                ('goods_sold', models.DecimalField(blank=True, decimal_places=2, help_text='Goods sold value', max_digits=10, null=True)),
                ('currently_shown', models.CharField(blank=True, help_text='Currently shown location', max_length=255, null=True)),
                ('shown_in_past', models.CharField(blank=True, help_text='Previously shown locations', max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, help_text='Keywords for search', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
            ],
            options={
                'verbose_name': 'Image Metadata',
                'verbose_name_plural': 'Image Metadata',
                'db_table': 'image_metadata',
                'ordering': ['image_file_name'],
            },
        ),
    ]
